name: Deploy to GitHub Pages

on:
  push:
    branches: [kohane] # 监听 kohane 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1：检出代码（必须带 uses）
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2：安装 Node.js (必须带 uses)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3：安装 pnpm (必须带 uses)
      - name: Install pnpm
        run: npm install -g pnpm@8

      # Step 4：缓存依赖 (必须带 uses)
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}--pnpm-

      # Step 5：安装依赖 (必须带 run)
      - name: Install Dependencies (pnpm)
        run: pnpm install
        env:
          CI: true

      # Step 6：构建项目 (必须带 run)
      - name: Build Project (pnpm)
        run: pnpm run build

      # Step 7：部署到 GitHub Pages (必须带 uses)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 指定构建输出目录
